apiVersion: apps/v1
kind: Deployment
metadata:
  name: peakyapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peakyapi
  template:
    metadata:
      labels:
        app: peakyapi
    spec:
      containers:
      - name: peakyapi
        image: imagesakstest.azurecr.io/vazquezfed82/peaky-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http-web-svc
